### ISSUE TITLE
RUCIO network configuration

### ISSUE THREAD

**Issue by egazzarr** [EOSC-Future/eosc-future-cern#13]
The RUCIO service should be configured with network type `LoadBalancer`. CERN OpenStack provides an [external load-balancing service](https://clouddocs.web.cern.ch/networking/load_balancing.html), which is automatically created with the cluster itself.

- [x] Make sure the lb is configured correctly and does support SSL
- [x] Set all required aliases to it
- [x] Set RUCIO values for service to the network type `LoadBalancer`
- [x] Install and check functionality

**Comment by goseind** [comment]
`loadbalancer.openstack.org/network-id:` is no longer needed in newer projects. The way to get the right ID is to run `OS_REGION_NAME=sdn1; openstack network list  -c ID -f value
798d00f3-2af9-48a0-a7c3-a26d909a2d64`
